
#include<iostream>
#include<windows.h>

int s;

main(){
       printf("\n Sei pronto... ? Digita 1 e.e \n");
       scanf("%d",&s);
       
       while(s==1)
       {
        printf("\n LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD \n");
        system("color 0a");
        
        printf("\n LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD \n");
        system("color 1b");
        
        printf("\n LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD\n");
        system("color 2c");
        
        printf("\n LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD\n");
        system("color 3d");
        
        printf("\n LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD\n");
        system("color 4e");
        
        printf("\n LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD LSD\n");
        system("color 5f");
       
        
       }
       
       printf("\n Non uscirai mai dal trip... e.e \n");
       
       system("pause");
       }
